name: Build Automation

variables:
  - template: env/global.parameters.yml
  - template: variables.yml
    parameters:
      adoAccountName: ${{ variables.adoAccountName }}

trigger:
  - main
  
stages:
  - stage: Build 
    jobs:
      - job: Build
        pool: 
          vmImage: windows-latest
        steps:
          - task: CopyFiles@2
            displayName: Copy Runbooks to Artifact directory
            inputs:
              SourceFolder: ${{ variables.pathToRunbooksDirectory }}
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishPipelineArtifact@1
            displayName: Publish Runbooks as Artifact
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: 'runbooks-$(Build.BuildId)'